### ISSUE TITLE
Compilation errors with lastest version of graph-cli

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/adchain-subgraph#4]
To reproduce:
- Take a fresh clone of this repo
- Run `yarn install` (pulls from graph-cli master branch)
- Run `yarn build --verbosity debug`

Compilation fails with a bunch of errors like this:

```
9/11 Compile subgraph 
Compile data source mapping: AdNetworks => <build>/AdNetworks/AdNetworks.wasm
ERROR TS2304: Cannot find name 'Store'.

   let store = Store.bind(event.blockHash)
               ~~~~~
 in index.ts(1184,14)
```

I traced this back to commit https://github.com/graphprotocol/graph-cli/commit/b68bcac6c999049333a52b8c2f98f82586e50f76 @leodasvacas

**Comment by leodasvacas** [comment]
Thanks Tim, `Store.bind` got removed, this subgraph needs to be updated to remove the `Store.bind` lines.
